name: PRMetrics
on:
 pull_request:
      branches: [ "main" ]
      types: [opened, synchronize, reopened]
jobs:
  stats:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: PR Metrics
        uses: microsoft/PR-Metrics@v1.6.1
        env:
          PR_METRICS_ACCESS_TOKEN: ${{ secrets.PRMETRICSTOKEN }}
        with:
          base-size: 200
          growth-rate: 2.0
          test-factor: 1.0
          file-matching-patterns: |
            **/*
            !Ignore.cs
          code-file-extensions: |
            cs
            ps1
        continue-on-error: true



